apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apple-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/egangithub1502/antigravity_repo.git
    targetRevision: main   # Important: change to your actual branch name
    path: argocd-deployment           # Correct folder
  destination:
    server: https://kubernetes.default.svc
    namespace: apple
  syncPolicy:
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - CreateNamespace=true
    - Timeout=600

