apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: apple-app-rollout
  namespace: apple
  labels:
    app: kube-app
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: kube-app-svc
      previewService: kube-app-preview-svc     # ADDED
      autoPromotionEnabled: false              # SAME
      scaleDownDelaySeconds: 0                 # ADDED (no auto scale-down)
  selector:
    matchLabels:
      app: kube-app
  template:
    metadata:
      labels:
        app: kube-app
        role: preview  
    spec:
      serviceAccountName: kube-stag-pvt-cluster-wl-id
      containers:
      - name: kubeappcontainer
        image: us-central1-docker.pkg.dev/stm-01/my-app-repo/html-nginx-app:latest
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        imagePullPolicy: Always

